(define-module (wyvernh home package-modules))
;;   #:use-module (wyvernh home packages emacs)
;;   #:use-module (wyvernh home packages engineering)
;;   #:use-module (wyvernh home packages programming)
;;   #:use-module (wyvernh home packages desktop)
;;   #:use-module (wyvernh home packages misc)
;;   #:use-module (wyvernh home packages core)
;;   #:use-module (wyvernh home packages nvidia)
;;   #:use-module (wyvernh home packages latex)
;;   #:use-module (wyvernh home packages wyvernh)
;;   #:export (%wyvernh-packages)
;;   #:export (%wyvernh-latex-packages)
;;   #:export (%wyvernh-nvidia-packages)
;;   #:export (%wyvernh-core-packages)
;;   #:export (%wyvernh-emacs-packages)
;;   #:export (%wyvernh-engineering-packages)
;;   #:export (%wyvernh-programming-packages)
;;   #:export (%wyvernh-desktop-packages)
;;   #:export (%wyvernh-misc-packages)
;;   #:export (%wyvernh-test-packages)
;;   #:export (%wyvernh-package-module-latex))

;; (define %wyvernh-package-module-latex %wyvernh-latex-packages)
;; (define %wyvernh-test-packages (list))
